<script setup lang="ts">
defineEmits(["back"]);
</script>

<template>
  <div class="privacy-page">
    <div class="back-btn-wrapper">
      <button @click="$emit('back')" class="back-btn">← Back to About</button>
    </div>

    <h2>Privacy Policy</h2>
    <p class="last-updated">Last updated: 26.2.2026</p>
    <p>
      This tool is an independent community-created calculator for WalkScape. It
      is not operated by Not a Cult Oy.
    </p>

    <section class="policy-section">
      <h3>1. Data Collected</h3>
      <p>This tool stores the following information:</p>
      <ul>
        <li>A randomly generated UUID stored in your browser's local storage.</li>
        <li>Game-related data you voluntarily input (items, levels, stats).</li>
        <li>Temporary server logs generated by the hosting environment.</li>
      </ul>
      <p>No usernames, email addresses, or identifying information are collected.</p>
    </section>

    <section class="policy-section">
      <h3>2. Purpose of Processing</h3>
      <p>The data is processed solely to:</p>
      <ul>
        <li>Provide calculator and optimization functionality.</li>
        <li>Allow returning users to retrieve their previously entered data.</li>
      </ul>
    </section>

    <section class="policy-section">
      <h3>3. Legal Basis</h3>
      <p>
        Processing is necessary for the performance of a service requested by
        the user (Article 6(1)(b) GDPR).
      </p>
    </section>

    <section class="policy-section">
      <h3>4. Storage and Retention</h3>
      <ul>
        <li>Your UUID is stored in your browser local storage.</li>
        <li>Game data is stored on the server and linked only to your UUID.</li>
        <li>Data is retained as long as your UUID remains active.</li>
        <li>
          You may delete your data at any time by clearing your browser storage
          or contacting us.
        </li>
      </ul>
    </section>

    <section class="policy-section">
      <h3>5. Hosting</h3>
      <p>
        This tool is hosted on infrastructure provided by Not a Cult Oy. Server
        infrastructure may generate standard technical logs (e.g., IP addresses)
        for security and operational purposes.
      </p>
    </section>

    <section class="policy-section">
      <h3>6. Data Sharing</h3>
      <p>No data is shared with third parties.</p>
    </section>

    <section class="policy-section">
      <h3>7. Your Rights</h3>
      <p>
        If you are located in the European Union, you have the right to:
      </p>
      <ul>
        <li>Request access to your data</li>
        <li>Request deletion of your data</li>
        <li>Request correction of inaccurate data</li>
      </ul>
      <p>
        To exercise these rights, contact:
        <a href="mailto:[contact email]">[contact email]</a>
      </p>
    </section>
  </div>
</template>

<style scoped lang="scss">
.privacy-page {
  display: flex;
  flex-direction: column;
  gap: $lg;
  padding: $xlg;

  .last-updated {
    opacity: 0.6;
    font-size: 0.9em;
  }

  .policy-section {
    display: flex;
    flex-direction: column;
    gap: $sm;

    ul {
      list-style-type: none;
      padding-left: $md;

      li {
        text-align: center;
      }
    }
  }
}

.back-btn-wrapper {
  align-self: flex-start;
  margin-bottom: $xlg;

  .back-btn {
    cursor: pointer;

    &:hover {
      opacity: 1;
      text-decoration: underline;
    }
  }
}
</style>
